### ISSUE TITLE
Radarr balcklisting

### ISSUE THREAD

**Issue by Skyline404** [Drapersniper/Qbitrr#5]
Strange things happens: when script detecting stalled downloads for sonarr it blacklisting them successfully, but for radarr only deletes from qbt and not blacklisting.

**Comment by Drapersniper** [comment]
What version or radar and sonarr are you currently using ?

**Comment by Skyline404** [comment]
Radarr: 3.2.2.5080
Sonarr: 3.0.6.1342

**Comment by Drapersniper** [comment]
I just pushed an update that should fix several issues - not you will need to wipe the qBitrr databases found in `~/config/qBitManager` as there have been changes to the database structure and a full migration is an overkill.

I suspect this issue will be fixed by the new changes - just wanted to confirm you were running radar v3 which you are.

**Comment by Skyline404** [comment]
Updated to latest commit,  removed databases, but still not blacklisting

**Comment by Drapersniper** [comment]
Not entirely sure then, try to enable trace logging to see what's happening. It's definitively working for me and I'm using the latest radarr release (develop branch)

**Comment by Drapersniper** [comment]
Actually I have an idea what may be the issue, the develop branch changed the parameter name from blacklist to blocklist, the script uses blocklist when making the POST call. I believe your version still expects blacklist. 

Although I thought the same should happen with sonarr if this was the case - if you turn on trace logging and you get a debug line saying "blocklisting ...." then my suspicion is true.

**Comment by Drapersniper** [comment]
I just pushed an update, no need to delete the databases for it, but it should work - I just tested it and it didn't have any issues and everything was processed correctly.

**Comment by Skyline404** [comment]
Yes, now works perfectly, thx a lot! You have a great tool, i think you should promote it somewhere on reddit maybe?
